### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by SethTisue** [scala/vscode-scala-syntax#13]
I assume the omission of an open source license in this repo is just an oversight.

@nicolasstucki could you add one?

(I'm doing a license audit of all scala/* repos)

**Comment by SethTisue** [comment]
or if this repo is abandoned, shall we just archive it? I see the last commit is from 5 months ago

even if it's abandoned, it would still be good to slap a license on it, in case some future seeker finds something useful in it they want to borrow

**Comment by olafurpg** [comment]
This repo is not abandoned, at least the official Scala syntax package in vscode uses it https://marketplace.visualstudio.com/items?itemName=scala-lang.scala 

There is a LICENSE.md file in the repo https://github.com/scala/vscode-scala-syntax/blob/master/LICENSE.md I suspect the choice of MIT is because the source is a fork of some original syntax package, but I'm not familiar with the history. @SethTisue Close as fixed?

**Comment by nicolasstucki** [comment]
Yes, it is not abandoned. The licence came from the project we forked.

**Comment by nicolasstucki** [comment]
I am not sure if we can change it. @SethTisue do you know if we can or should?

**Comment by SethTisue** [comment]
apparently I looked right at the `LICENSE.md` file without seeing it. sorry for the brain lapse, I looked at a lot of repos that day :-)

**Comment by SethTisue** [comment]
MIT is fine
