### ISSUE TITLE
Add support for meta.function-call

### ISSUE THREAD

**Issue by AdrianRaFo** [scala/vscode-scala-syntax#198]
I have noticed that the function/method calls don't get any color when I configure it using the `meta.function-call` scope:

**Settings.json:**
```
{
  "scope": "meta.function-call",
  "settings": {
    "foreground": "#82AAFF"
  }
}
```

I tested this in other languages and it works as expected using that scope. 
Am I using the wrong scope? Could this be added? 
Thanks in advance

**Comment by nicolasstucki** [comment]
Could you provide some examples where you would expect this coloring? And some example of the other languages as a guide.

**Comment by AdrianRaFo** [comment]
Here you can see a little example on scala:
![scala](https://user-images.githubusercontent.com/15971742/114420215-6b353600-9bb4-11eb-9000-42746e5bd537.png)

and the same in python:
![python](https://user-images.githubusercontent.com/15971742/114420225-6cfef980-9bb4-11eb-874a-4d6600039999.png)

and this is how I see the same scala code on IntelliJ:
![intellij scala](https://user-images.githubusercontent.com/15971742/114420885-075f3d00-9bb5-11eb-8565-bad4580bf749.png)

Notice that If I try to color the `source.scala` scope it colors all the code.

**Comment by MaximeKjaer** [comment]
I think we can implement something that highlights *some* function calls as `meta.function-call`, but this would only be an approximation of coloring all function calls. The simplest heuristic we can use is to assign `meta.function-call` for any identifier followed by `(` or `{`.

There are some cases where we cannot highlight correctly:

- Arity-0 function calls that omit parentheses (e.g. `reply` instead of `reply()`) &mdash; though this is [(mostly) dropped in Scala 3](https://dotty.epfl.ch/docs/reference/dropped-features/auto-apply.html)
- Calls to functions whose names starts with an uppercase letter. These are ambiguous with calls to the `apply` method of an object (e.g. `MyObject(1, 2, 3)` vs `MyFunction(1, 2, 3)`) &mdash; though in this case, I think we can just go with the convention that uppercased identifiers are names of types, and lowercased identifiers are for methods and variables. So function calls starting with an uppercase would not be assigned `meta.function-call`.

In general, coloring all function calls correctly would require information from the compiler about which identifiers correspond to function names. In VS Code terminology, we would need to write a [semantic highlighter](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide), but this project is a [syntax highlighter](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide). So I think some approximation definitely is acceptable for the scope of this project.

**Comment by AdrianRaFo** [comment]
Adding a color for the a `.` following a name and optionally `(` or `{` looks awesome

**Comment by nicolasstucki** [comment]
I do not really see how we could get this information syntactically. This is in the domain of semantic highlighting.

Consider the following cases

```scala
val x1 = ???
def x2 = ???
def x3() = ???
val x4: () => () = ???

x1 // not a function call
x2 // function call
x3() // function call
x4() // not a function call

p.x1 // not a function call
p.x2 // function call
p.x3() // function call
p.x4() // not a function call
```

**Comment by tgodzik** [comment]
Semantic highlighting is part of LSP, so we might make it work in Metals. We should already have most information needed in semanticdb and we added the project as part of GSoC, but I am not sure if anyone applied.

**Comment by Jentsch** [comment]
Think this issue is resolved. I just tried nicolasstucki's example and it's corretly highlighted with metals.

![grafik](https://github.com/user-attachments/assets/14dbf700-6a27-45ac-82d7-c8d7705f2135)

|            | x1, x4 | x2, x3  |
|------------|---|---|
| semantic token type | variable | method |
| foreground | variable.other.constant | entity.name.function.member |
|            | variable.other.constant variable.other.enummember | entity.name.function support.function support.constant.handlebars source.powershell variable.other.member entity.name.operator.custom-literal |   
| color | #0070C1 | #795E26 |
