### ISSUE TITLE
Highlighting issue in VSCODE for string interpolation s2

### ISSUE THREAD

**Issue by tiphdousset** [scala/vscode-scala-syntax#222]
In VSCODE the highlighting for s2 string interpolation seems to be broken. See screenshots
<img width="914" alt="correctHighlightingWithS" src="https://user-images.githubusercontent.com/12503594/137889790-57f0f1f1-c967-47ee-acb3-51254913d383.png">
<img width="905" alt="noHighlighitngWithS2" src="https://user-images.githubusercontent.com/12503594/137889798-9aff5d94-fa12-4a40-a64f-b59e3a1968f0.png">

**Comment by MaximeKjaer** [comment]
Good catch. I think the issue is that we use `alphaId` as the regex for the string interpolation tag, but we should probably use `plainid`.

A minimized example:

```scala
implicit class TestInterpolation(val sc: StringContext) extends AnyVal {
  def `this doesn't work`(args: Any*): String = "no"
  def test(args: Any*): String = "test"
  def test1(args: Any*): String = "test1"
  def test_+(args: Any*): String = "test_+"
}

val name = "world"

`this doesn't work`"hello $name" // this does not compile
test"hello $name"
test1"hello $name"
test_+"hello $name"
```

**Comment by som-snytt** [comment]
`plainid` in spec includes operators, which are not allowed. `alphaid` is not "only alphas" but idents starting with an alpha (upper or lower, distinguished for patterns).

TIL it accommodates `idrest`, the operator tail in `test_+`. I was recalling that you can't `s"$x_+"` which interpolates `x_` not `x_+`.

So, you can't `*"text"` which is too bad because it looks cool.
