### ISSUE TITLE
how to switch between scala 2 and 3?

### ISSUE THREAD

**Issue by 3tbraden** [scala/vscode-scala-syntax#236]
I have a scala file that I want to use scala 2, however the syntax highlight keep reporting scala 3 error(procedure syntax not supported). How can I use scala 2 syntax please?

**Comment by som-snytt** [comment]
Probably they will say please ask questions on the forum, but migration source level is for this use case. `-help` says
```
              -source  source version
                       Default 3.0
                       Choices 3.0, 3.1, future, 3.0-migration, future-migration
```
so I guess `-source 3.0-migration`. Not sure which features are supported in migration. Definitely not early defs.

**Comment by MaximeKjaer** [comment]
Hi! This VS Code extension only provides highlighting for Scala. It does so for both Scala 2 and 3, and does not detect whether you're using one or the other. This extension actually doesn't use the compiler; instead, it only gives a description of Scala's grammar for the purpose of highlighting Scala code in VS Code.

It sounds like you might be getting an error from Metals using the Scala 3 compiler instead of Scala 2 for your project. If so, perhaps the [Metals docs](https://scalameta.org/metals/docs/editors/vscode) may contain some advice on how to configure your editor to use Scala 2 instead of 3.

Let me know if that resolves your issue!

**Comment by 3tbraden** [comment]
thanks for the replies! I didn't know there's a forum, sorry for intruding here! I have briefly checked how to specify scala version in Metals but haven't found anything useful yet.

I will close this issue now as this is not in the scope of this project.
