### ISSUE TITLE
How does it compare against the other 2 syntax extensions?

### ISSUE THREAD

**Issue by dragos** [scala/vscode-scala-syntax#4]
There seems to be at least 3 different syntax bundles on the market place. This one being the latest, it should justify its existence. What makes it different from the other 2?

**Comment by smarter** [comment]
The point of this extension is to be an officially and actively maintained extension that every language server for Scala can depend on instead of using an unmaintained one from the marketplace or reinventing their own. This hasn't happened so far, but hopefully will in the near future as we start using it for Dotty and hopefully metals
