### ISSUE TITLE
Broken coloring of identifiers with letters ÅÄÖ åäö

### ISSUE THREAD

**Issue by bjornregnell** [scala/vscode-scala-syntax#5]
If letters åäö or ÅÄÖ (used e.g. in Swedish, German etc) appear in an identifier the coloring breaks:
![scala](https://user-images.githubusercontent.com/3601817/40055636-e3dd4e60-5848-11e8-98eb-d7c3dcb0d2c8.png)
It works for Java though using the built in java syntax package:
![java](https://user-images.githubusercontent.com/3601817/40055708-2513e970-5849-11e8-925c-f8c556644330.png)
Tested in vscode v1.23.1 using vscode-scala-syntax v0.1.2
The bug only appears in some color themes, e.g. Dark+ (default dark) and Monokai Dimmed. Above images grabbed with color theme Atom One Dark.

**Comment by wpug** [comment]
The bug is still there (for the Polish letters in my case – such as ą,ę,ś,ć etc). It appears in some color themes only, because only some of them seem to distinguish identifier declarations... If it is not possible to make the highlighting work "in general" then maybe a configuration option for "allowed identifier symbols" can be added?

**Comment by olafurpg** [comment]
This fix has now been released as part of 0.3.2 (https://github.com/scala/vscode-scala-syntax/releases/tag/v0.3.2), thank you for reporting!
